spring.docker.compose.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/meditrack
spring.datasource.username=meditrack
spring.datasource.password=meditrack

spring.jpa.show-sql=true

spring.elasticsearch.uris=http://localhost:9200

logging.level.dev.zisan.meditrack=DEBUG
logging.level.org.springframework.web=INFO
